// Rest-timer "done" cue: a preloaded <audio> element playing the synthesized gong
// (public/gong.mp3, generated by scripts/make-gong.mjs). Mobile browsers block audio
// until a user gesture, so unlockAudio() must run inside a tap (we call it from the
// set-complete ✓ — the same tap that starts the rest) to prime playback for when the
// timer later fires from a setInterval callback (not a gesture).
const GONG_URL = `${import.meta.env.BASE_URL}gong.mp3`

let el: HTMLAudioElement | null = null
let unlocked = false

function audio(): HTMLAudioElement {
  if (!el) {
    el = new Audio(GONG_URL)
    el.preload = 'auto'
  }
  return el
}

/**
 * Prime audio within a user gesture so it can play later from a timer callback.
 * Plays MUTED then resets (iOS ignores `volume` but honours `muted`), so there's no
 * audible blip on the unlocking tap. Safe to call repeatedly; no-ops once unlocked.
 */
export function unlockAudio(): void {
  if (unlocked) return
  const a = audio()
  a.muted = true
  a.play()
    .then(() => { a.pause(); a.currentTime = 0; a.muted = false; unlocked = true })
    .catch(() => { a.muted = false /* not unlocked; retry on the next gesture */ })
}

/** Play the gong from the start. No-op-safe if the browser still blocks it. */
export function playRestDone(): void {
  const a = audio()
  a.muted = false
  try { a.currentTime = 0 } catch { /* not ready yet */ }
  void a.play().catch(() => { /* blocked — the vibration still fires */ })
}
